title: Goldslime Kingdom!
description: >
  **I am Goldslime**, Um, nice to meet you!
copyright: 2015-2016 goldslime88.github.io
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: goldslime88
github_username:  "goldslime88"
email: "cljjohn88@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
