title: Goldslime Kingdom!
description: >
  **I am Strata**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP](http://html5up.net).
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: goldslime88
github_username:  "goldslime88"
email: "cljjohn88@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
